# Generated by Django 5.0.6 on 2024-09-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Report",
        ),
    ]
